### ISSUE TITLE
variable value shows as *****

### ISSUE THREAD

**Issue by jeremysimmons** [qetza/vsts-xdttransform-task#2]
using transformations: web.test.config => web.config
I have a build variable: BuildEnvironment = test
the output of the task reads as: 
```
2017-02-27T20:51:10.3694896Z ##[section]Starting: Apply transforms web.********.config => web.config
2017-02-27T20:51:11.6174896Z Applying transformations 'D:\TFS2017Build\Agent1\_work\1\a\web.********.config' on file 'D:\TFS2017Build\Agent1\_work\1\a\web.config'...
2017-02-27T20:51:11.7110896Z ##[section]Finishing: Apply transforms web.********.config => web.config
```

Is this part of the TFS Logging, or is the task doing this replacement?
![pic1](https://cloud.githubusercontent.com/assets/1406886/23380111/c9137ac2-fcf6-11e6-890f-03882cd92344.png)

![pic2](https://cloud.githubusercontent.com/assets/1406886/23380121/d08595c4-fcf6-11e6-93b4-24acc7e77b41.png)

**Comment by qetza** [comment]
Hi @jeremysimmons,
What you see is a features of the TFS logging which replaces secret variable values with ****** to avoir any leak.
I would say that you have one secret variable with the value "test" and that's why you see web.******.config.

Guillaume

**Comment by jeremysimmons** [comment]
We have two secure variables
LoginName
webTestSharePassword

Other tasks (Build solution, Copy Files) in do not mask out this value.

**Comment by qetza** [comment]
Hi Jeremy,
I've done the following test:
A build with just a transform task and a variable `BuildEnvironment` with value `test`:
![image](https://cloud.githubusercontent.com/assets/8191369/23448076/2c229e78-fe4f-11e6-94fc-dfbc185638c2.png)

Here the log is correct and the transformation was done as expected.

I've then added a secret variable `Password` with the value `test`:
![image](https://cloud.githubusercontent.com/assets/8191369/23448116/5d2c6f4e-fe4f-11e6-9d32-d841faed6a54.png)

The `test` text in the log was hidden but the transformation was also done as expected. This secret value masking is part of the TFS agent which simply parses the log and mask any secret variable values.

**Comment by qetza** [comment]
I'm closing the issue, feel free to reopen if needed.
