### ISSUE TITLE
Issue with env block size limit

### ISSUE THREAD

**Issue by RomanDidenko** [qetza/vsts-xdttransform-task#24]
Can you please update VstsTaskSdk to at least version 0.8.2 as I am faced with env block size limit issue that has been fixed [here](https://github.com/microsoft/azure-pipelines-task-lib/issues/228) by vsts team?

**Comment by qetza** [comment]
Hi @RomanDidenko,
Thanks for the feedback, i'll try to update to the latest sdk as soon as possible.

**Comment by davislabs** [comment]
Encountering the same problem.  If you have a large number of artifacts on the pipeline, pretty easy to go over this block size limit.

**Comment by qetza** [comment]
Hi @RomanDidenko, @davislabs,
Version 3.1.0 is released and was updated to the latest SDK version.

**Comment by RomanDidenko** [comment]
Thank you! Much appreciated
