### ISSUE TITLE
Multiple config transforms in one step unable to save tfs 2017

### ISSUE THREAD

**Issue by techz7** [qetza/vsts-xdttransform-task#4]
Hello,

I am trying to perform all of the configs in a single step in TFS2017, ex below:
Web.Dev.config => web.config => Web.Dev.config
Web.Tst.config => web.config => Web.Tst.config

When you go to save it Is giving an error for illegal characters and not allowing a save when I opened the network call it looks like it is sending the content as having a return carriage in it 
![image](https://cloud.githubusercontent.com/assets/6581754/26417305/ab4bc2b4-406d-11e7-926e-f95057f9f27a.png)

Trying to perform all of the transforms on one line will allow a save but doesn't transform either file

**Comment by qetza** [comment]
Hi @techz7,

It seems there is a bug in TFS 2017 where it doesn't automatically remove illegal characters when generating the display name of the task. I will do some test on my side, which version of TFS 2017 are you using? Are you using the old build editor or the new one?

As a workaround you can change manually the display name of the task to remove the carriage return and you should be able to save.

**Comment by techz7** [comment]
Is there a way to comma delimit it?

**Comment by qetza** [comment]
Currently no but i will add this to the backlog.

**Comment by qetza** [comment]
Hi @techz7,
I've added support for comma delimiter in version 2.1.0.
