### ISSUE TITLE
Exception calling "Save" with "1" argument(s): "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by aminebz949904** [qetza/vsts-xdttransform-task#9]
Hi,

I'm using vsts xdt transform task, and it's returning the following error:

Exception calling "Save" with "1" argument(s): "Object reference not set to an instance of an object."

Any help?

![image](https://user-images.githubusercontent.com/29580135/31236174-508c999c-a9eb-11e7-8b37-59dc84f87e81.png)

Thanks

**Comment by qetza** [comment]
Hi @aminebz949904,

I'll look into this. Could you tell me which version of powershell you have installed on your build server and which version of the .net framework?

Thanks

**Comment by aminebz949904** [comment]
Hi qetza,

Thank you for your help..

Powershell version on the build server is:

Major  Minor  Build     Revision
5         1          14393   1715

.net version 4.5.2

Thank you

**Comment by aminebz949904** [comment]
Hi,

Actually, I have used

 xdt:Transform="SetAttributes(ApplicationTypeName)" 

instead of: xdt:Transform="Replace"

And it worked fine.

Thank you for your help.
